# Ensures all xmake compile tests pass on windows for every RHI
name: Windows

on:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
    
        strategy:
            fail-fast: false

            matrix:
                build-config: [ debug]
                rhi: [ dx11 ] # We currently do not support the other API's
                # rhi: [ dx11, dx12, opengl, vulkan ]
        
        steps:
            - uses: actions/checkout@v4
            - uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: latest
                  actions-cache-folder: '.xmake-cache'
                  
            - name: Set RHI and build config
              run: |
                  xmake f --file=${GITHUB_WORKSPACE}/xmake.lua --rhi=${{ matrix.rhi }} -m ${{ matrix.build-config }} -y
                  
            - name: Build
              run: |
                  xmake build --file=${GITHUB_WORKSPACE}/xmake.lua --all -y -vD
